{"name": "Вход курьера с неверным  логином", "status": "passed", "description": "Ожидаемый результат не совпадает с фактическим. Помимо сообщения выводится код отввета 404", "start": 1724601128616, "stop": 1724601128825, "uuid": "9877986f-a448-45b3-8fb0-3902ba7109c7", "historyId": "b4c1edb660c77048f148f0c25323caf8", "testCaseId": "b4c1edb660c77048f148f0c25323caf8", "fullName": "tests.test_api_sign_in.test_api_sign_in_post.TestApiSignInPost#test_sign_in_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "tests.test_api_sign_in"}, {"name": "suite", "value": "test_api_sign_in_post"}, {"name": "subSuite", "value": "TestApiSignInPost"}, {"name": "host", "value": "MacBook-Pro-2.local"}, {"name": "thread", "value": "64895-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_sign_in.test_api_sign_in_post"}]}